version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Amsterdam

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "18:00"
      timezone: Europe/Amsterdam
